#' Assert that an input is a vector/list with desired properties
#'
#' @param x A vector. The input to be analysed.
#' @param class A string. The class that this input should inherit from.
#' @param len An integer. The length of the vector. If `NULL`, length is not
#'   checked.
#' @param null_ok A logical. Whether the input could also be `NULL`.
#' @param var_name A string. The name of the variable in the informative
#'   message. If `NULL`, the name is guessed from the function call.
#' @param n_call A negative integer. The number of frames to go back to find the
#'   call to associate the error generated by the function with. Defaults to the
#'   parent frame (-1). This argument is only relevant to other assertion
#'   functions that build on top of this one.
#'
#' @return `TRUE` if the check is successful. Throws an error describing the
#'   issue with the input otherwise.
#'
#' @family input assertion
#'
#' @keywords internal
assert_vector <- function(x,
                          class,
                          len = NULL,
                          null_ok = FALSE,
                          var_name = NULL,
                          n_call = -1L) {

  # basic input checking

  if (!(is.character(class) && length(class) == 1))
    stop("'class' must be a string.")

  if (!is.null(len) && !(is.integer(len) && length(len) == 1))
    stop("'length' must be an integer vector with length 1.")

  if (!(is.logical(null_ok) && length(null_ok) == 1))
    stop("'null_ok' must be a logical vector with length 1.")

  if (!is.null(var_name) && !(is.character(var_name) && length(var_name) == 1))
    stop("'var_name' must be a string.")

  if (!(is.integer(n_call) && length(n_call) == 1 && n_call < 0))
    stop("'n_call' must be a negative integer.")

  # construct input_name either from 'var_name' or from function call

  current_call <- sys.call(0)
  input_name <- as.character(current_call[[2]])

  if (!is.null(var_name)) input_name <- var_name

  # objects to create the gtfsio_error

  error_call <- sys.call(n_call)
  input_error_class <- paste0("bad_", input_name, "_argument")

  input_name <- paste0("'", input_name, "'")
  vector_name <- ifelse(
    class == "list",
    "a list.",
    paste0("a(n) ", class, " vector.")
  )

  # check against desired properties
  # the complicated logical condition below checks for the possibility of 'x'
  # being NULL is null_ok is TRUE

  if ((!inherits(x, class) && null_ok && !is.null(x))
    || (!inherits(x, class) && !null_ok)) {

    gtfsio_error(
      paste0(input_name, " must be ", vector_name),
      input_error_class,
      error_call
    )

  }

  if (!is.null(len) && len != length(x))
    gtfsio_error(
      paste0(input_name, " must have length ", len, "."),
      input_error_class,
      error_call
    )

  invisible(TRUE)

}



#' @rdname assert_vector
#' @family input assertion
#' @export
assert_list <- function(x, len = NULL, null_ok = FALSE) {

  # input checks are all conducted inside assert_vector()

  call <- sys.call(0)
  var_name <- as.character(call[[2]])

  assert_vector(
    x,
    "list",
    len = len,
    null_ok = null_ok,
    var_name = var_name,
    n_call = -2L
  )

}

